### ISSUE TITLE
Changing library folder

### ISSUE THREAD

**Issue by memnos** [iam4x/bobarr#113]
Hello,
changed library location to get my movies and series.

I use a remote drive mounted with rclone in /media/rclone
Inside it i have 2 folders Movies and Serie_Tv

I created a new dir /media/bobarr and made 2 symbolic links named movies and tvshoes pointing to /media/rclone/Movies and  /media/rclone/Serie_Tv.

Than I changed like this:
Change in docker-compose.yml the folder link - ./library:/usr/library
Point to your own library folder - /media/bobarr:/usr/library

But when i make scan library folder i cannot find anything.

What am i doing wrong?

**Comment by memnos** [comment]
I've updated bobarr and changed folder names in .env file.


After running scan library i have this error and nothing is scanned:

`null value in column "seasonId" violates not-null constraint
QueryFailedError: null value in column "seasonId" violates not-null constraint
    at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:138:19)
    at Connection.connectedErrorMessageHandler (/usr/src/app/node_modules/pg/lib/client.js:223:17)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:120:12)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)`

**Comment by iam4x** [comment]
How is your folder structure in your tv shows folder? It should look something like that:

![image](https://user-images.githubusercontent.com/893837/84359881-92545d00-abc9-11ea-85b3-0056892d976d.png)

**Comment by memnos** [comment]
It is like this
It seems just like yours.

Serie_Tv/
├── Breaking Bad
│   ├── Season01
│   ├── Season02
│   ├── Season03
│   ├── Season04
│   └── Season05
├── Carnival Row
│   └── Season01

**Comment by iam4x** [comment]
Ok, do you have any line in err.log with:

* `could not parse season number`
* `could not parse episode number`

Can you show me how your episodes are named as well?

**Comment by memnos** [comment]
Sorry, but i can't find any files named error.log in packages/api or in any folder under bobarr

Here are names.
I don't know if it can make problems but i have also other files inside those dir, as posters and so on.

Serie_Tv/
├── Breaking Bad
│   ├── Season01
│   │   ├── Breaking Bad.S01E01.Pilot.mkv
│   │   ├── Breaking Bad.S01E02.Cat's in the Bag.mkv
│   │   ├── Breaking Bad.S01E03.And the Bag's in the River.mkv
│   │   ├── Breaking Bad.S01E04.Cancer Man.mkv
│   │   ├── Breaking Bad.S01E05.Gray Matter.mkv
│   │   ├── Breaking Bad.S01E06.Crazy Handful of Nothin'.mkv
│   │   └── Breaking Bad.S01E07.A No-Rough-Stuff-Type Deal.mkv
│   ├── Season02
│   │   ├── Breaking Bad.S02E01.Seven Thirty-Seven.mkv
│   │   ├── Breaking Bad.S02E02.Grilled.mkv
│   │   ├── Breaking Bad.S02E03.Bit by a Dead Bee.mkv
│   │   ├── Breaking Bad.S02E04.Down.mkv
│   │   ├── Breaking Bad.S02E05.Breakage.mkv
│   │   ├── Breaking Bad.S02E06.Peekaboo.mkv
│   │   ├── Breaking Bad.S02E07.Negro y Azul.mkv
│   │   ├── Breaking Bad.S02E08.Better Call Saul.mkv
│   │   ├── Breaking Bad.S02E09.4 Days Out.mkv
│   │   ├── Breaking Bad.S02E10.Over.mkv
│   │   ├── Breaking Bad.S02E11.Mandala.mkv
│   │   ├── Breaking Bad.S02E12.Phoenix.mkv
│   │   └── Breaking Bad.S02E13.ABQ.mkv
│   ├── Season03
│   │   ├── Breaking Bad.S03E01.No Mas.mkv
│   │   ├── Breaking Bad.S03E02.Caballo Sin Nombre.mkv
│   │   ├── Breaking Bad.S03E03.I.F.T.mkv
│   │   ├── Breaking Bad.S03E04.Green Light.mkv
│   │   ├── Breaking Bad.S03E05.Mas.mkv
│   │   ├── Breaking Bad.S03E06.Sunset.mkv
│   │   ├── Breaking Bad.S03E07.One Minute.mkv
│   │   ├── Breaking Bad.S03E08.I See You.mkv
│   │   ├── Breaking Bad.S03E09.Kafkaesque.mkv
│   │   ├── Breaking Bad.S03E10.Fly.mkv
│   │   ├── Breaking Bad.S03E11.Abiquiu.mkv
│   │   ├── Breaking Bad.S03E12.Half Measures.mkv
│   │   └── Breaking Bad.S03E13.Full Measure.mkv
│   ├── Season04
│   │   ├── Breaking Bad.S04E01.Box Cutter.mkv
│   │   ├── Breaking Bad.S04E02.Thirty-Eight Snub.mkv
│   │   ├── Breaking Bad.S04E03.Open House.mkv
│   │   ├── Breaking Bad.S04E04.Bullet Points.mkv
│   │   ├── Breaking Bad.S04E05.Shotgun.mkv
│   │   ├── Breaking Bad.S04E06.Cornered.mkv
│   │   ├── Breaking Bad.S04E07.Problem Dog.mkv
│   │   ├── Breaking Bad.S04E08.Hermanos.mkv
│   │   ├── Breaking Bad.S04E09.Bug.mkv
│   │   ├── Breaking Bad.S04E10.Salud.mkv
│   │   ├── Breaking Bad.S04E11.Crawl Space.mkv
│   │   ├── Breaking Bad.S04E12.End Times.mkv
│   │   └── Breaking Bad.S04E13.Face Off.mkv
│   └── Season05
│       ├── Breaking Bad.S05E01.Live Free or Die.mkv
│       ├── Breaking Bad.S05E02.Madrigal.mkv
│       ├── Breaking Bad.S05E03.Hazard Pay.mkv
│       ├── Breaking Bad.S05E04.Fifty-One.mkv
│       ├── Breaking Bad.S05E05.Dead Freight.mkv
│       ├── Breaking Bad.S05E06.Buyout.mkv
│       ├── Breaking Bad.S05E07.Say My Name.mkv
│       ├── Breaking Bad.S05E08.Gliding Over All.mkv
│       ├── Breaking Bad.S05E09.Blood Money.mkv
│       ├── Breaking Bad.S05E10.Buried.mkv
│       ├── Breaking Bad.S05E11.Confessions.mkv
│       ├── Breaking Bad.S05E12.Rabid Dog.mkv
│       ├── Breaking Bad.S05E13.To'hajiilee.mkv
│       ├── Breaking Bad.S05E14.Ozymandias.mkv
│       ├── Breaking Bad.S05E15.Granite State.mkv
│       └── Breaking Bad.S05E16.Felina.mkv
├── Carnival Row
│   └── Season01
│       ├── Carnival Row.S01E01.Some Dark God Wakes.mkv
│       ├── Carnival Row.S01E02.Aisling.mkv
│       ├── Carnival Row.S01E03.Kingdoms of the Moon.mkv
│       ├── Carnival Row.S01E04.The Joining of Unlike Things.mkv
│       ├── Carnival Row.S01E05.Grieve No More.mkv
│       ├── Carnival Row.S01E06.Unaccompanied Fae.mkv
│       ├── Carnival Row.S01E07.The World to Come.mkv
│       └── Carnival Row.S01E08.The Gloaming.mkv

**Comment by iam4x** [comment]
Oh yes posters or other files may impacts, the files list like you did is perfect I would be able to reproduce. Can you give me an example with other files names?

**Comment by memnos** [comment]
Here is the complete tree:

Serie_Tv/
├── Breaking Bad
│   ├── clearlogo.png
│   ├── fanart.jpg
│   ├── poster.jpg
│   ├── Season01
│   │   ├── Breaking Bad.S01E01.Pilot.it.srt
│   │   ├── Breaking Bad.S01E01.Pilot.mkv
│   │   ├── Breaking Bad.S01E01.Pilot.nfo
│   │   ├── Breaking Bad.S01E01.Pilot-thumb.jpg
│   │   ├── Breaking Bad.S01E02.Cat's in the Bag.it.srt
│   │   ├── Breaking Bad.S01E02.Cat's in the Bag.mkv
│   │   ├── Breaking Bad.S01E02.Cat's in the Bag.nfo
│   │   ├── Breaking Bad.S01E02.Cat's in the Bag-thumb.jpg
│   │   ├── Breaking Bad.S01E03.And the Bag's in the River.it.srt
│   │   ├── Breaking Bad.S01E03.And the Bag's in the River.mkv
│   │   ├── Breaking Bad.S01E03.And the Bag's in the River.nfo
│   │   ├── Breaking Bad.S01E03.And the Bag's in the River-thumb.jpg
│   │   ├── Breaking Bad.S01E04.Cancer Man.it.srt
│   │   ├── Breaking Bad.S01E04.Cancer Man.mkv
│   │   ├── Breaking Bad.S01E04.Cancer Man.nfo
│   │   ├── Breaking Bad.S01E04.Cancer Man-thumb.jpg
│   │   ├── Breaking Bad.S01E05.Gray Matter.it.srt
│   │   ├── Breaking Bad.S01E05.Gray Matter.mkv
│   │   ├── Breaking Bad.S01E05.Gray Matter.nfo
│   │   ├── Breaking Bad.S01E05.Gray Matter-thumb.jpg
│   │   ├── Breaking Bad.S01E06.Crazy Handful of Nothin'.it.srt
│   │   ├── Breaking Bad.S01E06.Crazy Handful of Nothin'.mkv
│   │   ├── Breaking Bad.S01E06.Crazy Handful of Nothin'.nfo
│   │   ├── Breaking Bad.S01E06.Crazy Handful of Nothin'-thumb.jpg
│   │   ├── Breaking Bad.S01E07.A No-Rough-Stuff-Type Deal.it.srt
│   │   ├── Breaking Bad.S01E07.A No-Rough-Stuff-Type Deal.mkv
│   │   ├── Breaking Bad.S01E07.A No-Rough-Stuff-Type Deal.nfo
│   │   └── season.nfo
│   ├── season01-poster.jpg
│   ├── Season02
│   │   ├── Breaking Bad.S02E01.Seven Thirty-Seven.mkv
│   │   ├── Breaking Bad.S02E01.Seven Thirty-Seven.nfo
│   │   ├── Breaking Bad.S02E01.Seven Thirty-Seven-thumb.jpg
│   │   ├── Breaking Bad.S02E02.Grilled.mkv
│   │   ├── Breaking Bad.S02E02.Grilled.nfo
│   │   ├── Breaking Bad.S02E02.Grilled-thumb.jpg
│   │   ├── Breaking Bad.S02E03.Bit by a Dead Bee.mkv
│   │   ├── Breaking Bad.S02E03.Bit by a Dead Bee.nfo
│   │   ├── Breaking Bad.S02E04.Down.mkv
│   │   ├── Breaking Bad.S02E04.Down.nfo
│   │   ├── Breaking Bad.S02E04.Down.srt
│   │   ├── Breaking Bad.S02E05.Breakage.mkv
│   │   ├── Breaking Bad.S02E05.Breakage.nfo
│   │   ├── Breaking Bad.S02E06.Peekaboo.mkv
│   │   ├── Breaking Bad.S02E06.Peekaboo.nfo
│   │   ├── Breaking Bad.S02E06.Peekaboo-thumb.jpg
│   │   ├── Breaking Bad.S02E07.Negro y Azul.it.srt
│   │   ├── Breaking Bad.S02E07.Negro y Azul.mkv
│   │   ├── Breaking Bad.S02E07.Negro y Azul.nfo
│   │   ├── Breaking Bad.S02E08.Better Call Saul.it.srt
│   │   ├── Breaking Bad.S02E08.Better Call Saul.mkv
│   │   ├── Breaking Bad.S02E08.Better Call Saul.nfo
│   │   ├── Breaking Bad.S02E09.4 Days Out.it.srt
│   │   ├── Breaking Bad.S02E09.4 Days Out.mkv
│   │   ├── Breaking Bad.S02E09.4 Days Out.nfo
│   │   ├── Breaking Bad.S02E10.Over.it.srt
│   │   ├── Breaking Bad.S02E10.Over.mkv
│   │   ├── Breaking Bad.S02E10.Over.nfo
│   │   ├── Breaking Bad.S02E11.Mandala.it.srt
│   │   ├── Breaking Bad.S02E11.Mandala.mkv
│   │   ├── Breaking Bad.S02E11.Mandala.nfo
│   │   ├── Breaking Bad.S02E11.Mandala-thumb.jpg
│   │   ├── Breaking Bad.S02E12.Phoenix.it.srt
│   │   ├── Breaking Bad.S02E12.Phoenix.mkv
│   │   ├── Breaking Bad.S02E12.Phoenix.nfo
│   │   ├── Breaking Bad.S02E13.ABQ.it.srt
│   │   ├── Breaking Bad.S02E13.ABQ.mkv
│   │   └── Breaking Bad.S02E13.ABQ.nfo
│   ├── season02-fanart.jpg
│   ├── season02-poster.jpg
│   ├── Season03
│   │   ├── Breaking Bad.S03E01.No Mas.it.srt
│   │   ├── Breaking Bad.S03E01.No Mas.mkv
│   │   ├── Breaking Bad.S03E01.No Mas.nfo
│   │   ├── Breaking Bad.S03E02.Caballo Sin Nombre.it.srt
│   │   ├── Breaking Bad.S03E02.Caballo Sin Nombre.mkv
│   │   ├── Breaking Bad.S03E02.Caballo Sin Nombre.nfo
│   │   ├── Breaking Bad.S03E03.I.F.T.it.srt
│   │   ├── Breaking Bad.S03E03.I.F.T.mkv
│   │   ├── Breaking Bad.S03E03.I.F.T.nfo
│   │   ├── Breaking Bad.S03E04.Green Light.it.srt
│   │   ├── Breaking Bad.S03E04.Green Light.mkv
│   │   ├── Breaking Bad.S03E04.Green Light.nfo
│   │   ├── Breaking Bad.S03E05.Mas.it.srt
│   │   ├── Breaking Bad.S03E05.Mas.mkv
│   │   ├── Breaking Bad.S03E05.Mas.nfo
│   │   ├── Breaking Bad.S03E06.Sunset.it.srt
│   │   ├── Breaking Bad.S03E06.Sunset.mkv
│   │   ├── Breaking Bad.S03E06.Sunset.nfo
│   │   ├── Breaking Bad.S03E07.One Minute.it.srt
│   │   ├── Breaking Bad.S03E07.One Minute.mkv
│   │   ├── Breaking Bad.S03E07.One Minute.nfo
│   │   ├── Breaking Bad.S03E08.I See You.it.srt
│   │   ├── Breaking Bad.S03E08.I See You.mkv
│   │   ├── Breaking Bad.S03E08.I See You.nfo
│   │   ├── Breaking Bad.S03E09.Kafkaesque.it.srt
│   │   ├── Breaking Bad.S03E09.Kafkaesque.mkv
│   │   ├── Breaking Bad.S03E09.Kafkaesque.nfo
│   │   ├── Breaking Bad.S03E10.Fly.it.srt
│   │   ├── Breaking Bad.S03E10.Fly.mkv
│   │   ├── Breaking Bad.S03E10.Fly.nfo
│   │   ├── Breaking Bad.S03E11.Abiquiu.it.srt
│   │   ├── Breaking Bad.S03E11.Abiquiu.mkv
│   │   ├── Breaking Bad.S03E11.Abiquiu.nfo
│   │   ├── Breaking Bad.S03E12.Half Measures.it.srt
│   │   ├── Breaking Bad.S03E12.Half Measures.mkv
│   │   ├── Breaking Bad.S03E12.Half Measures.nfo
│   │   ├── Breaking Bad.S03E13.Full Measure.it.srt
│   │   ├── Breaking Bad.S03E13.Full Measure.mkv
│   │   ├── Breaking Bad.S03E13.Full Measure.nfo
│   │   └── season.nfo
│   ├── season03-poster.jpg
│   ├── Season04
│   │   ├── Breaking Bad.S04E01.Box Cutter.it.srt
│   │   ├── Breaking Bad.S04E01.Box Cutter.mkv
│   │   ├── Breaking Bad.S04E01.Box Cutter.nfo
│   │   ├── Breaking Bad.S04E02.Thirty-Eight Snub.it.srt
│   │   ├── Breaking Bad.S04E02.Thirty-Eight Snub.mkv
│   │   ├── Breaking Bad.S04E02.Thirty-Eight Snub.nfo
│   │   ├── Breaking Bad.S04E03.Open House.it.srt
│   │   ├── Breaking Bad.S04E03.Open House.mkv
│   │   ├── Breaking Bad.S04E03.Open House.nfo
│   │   ├── Breaking Bad.S04E04.Bullet Points.it.srt
│   │   ├── Breaking Bad.S04E04.Bullet Points.mkv
│   │   ├── Breaking Bad.S04E04.Bullet Points.nfo
│   │   ├── Breaking Bad.S04E05.Shotgun.it.srt
│   │   ├── Breaking Bad.S04E05.Shotgun.mkv
│   │   ├── Breaking Bad.S04E05.Shotgun.nfo
│   │   ├── Breaking Bad.S04E06.Cornered.it.srt
│   │   ├── Breaking Bad.S04E06.Cornered.mkv
│   │   ├── Breaking Bad.S04E06.Cornered.nfo
│   │   ├── Breaking Bad.S04E07.Problem Dog.it.srt
│   │   ├── Breaking Bad.S04E07.Problem Dog.mkv
│   │   ├── Breaking Bad.S04E07.Problem Dog.nfo
│   │   ├── Breaking Bad.S04E08.Hermanos.it.srt
│   │   ├── Breaking Bad.S04E08.Hermanos.mkv
│   │   ├── Breaking Bad.S04E08.Hermanos.nfo
│   │   ├── Breaking Bad.S04E09.Bug.it.srt
│   │   ├── Breaking Bad.S04E09.Bug.mkv
│   │   ├── Breaking Bad.S04E09.Bug.nfo
│   │   ├── Breaking Bad.S04E10.Salud.it.srt
│   │   ├── Breaking Bad.S04E10.Salud.mkv
│   │   ├── Breaking Bad.S04E10.Salud.nfo
│   │   ├── Breaking Bad.S04E11.Crawl Space.it.srt
│   │   ├── Breaking Bad.S04E11.Crawl Space.mkv
│   │   ├── Breaking Bad.S04E11.Crawl Space.nfo
│   │   ├── Breaking Bad.S04E12.End Times.it.srt
│   │   ├── Breaking Bad.S04E12.End Times.mkv
│   │   ├── Breaking Bad.S04E12.End Times.nfo
│   │   ├── Breaking Bad.S04E13.Face Off.it.srt
│   │   ├── Breaking Bad.S04E13.Face Off.mkv
│   │   ├── Breaking Bad.S04E13.Face Off.nfo
│   │   ├── Breaking Bad.S04E13.Face Off-thumb.jpg
│   │   └── season.nfo
│   ├── season04-poster.jpg
│   ├── Season05
│   │   ├── Breaking Bad.S05E01.Live Free or Die.it.srt
│   │   ├── Breaking Bad.S05E01.Live Free or Die.mkv
│   │   ├── Breaking Bad.S05E01.Live Free or Die.nfo
│   │   ├── Breaking Bad.S05E02.Madrigal.it.srt
│   │   ├── Breaking Bad.S05E02.Madrigal.mkv
│   │   ├── Breaking Bad.S05E02.Madrigal.nfo
│   │   ├── Breaking Bad.S05E03.Hazard Pay.it.srt
│   │   ├── Breaking Bad.S05E03.Hazard Pay.mkv
│   │   ├── Breaking Bad.S05E03.Hazard Pay.nfo
│   │   ├── Breaking Bad.S05E04.Fifty-One.it.srt
│   │   ├── Breaking Bad.S05E04.Fifty-One.mkv
│   │   ├── Breaking Bad.S05E04.Fifty-One.nfo
│   │   ├── Breaking Bad.S05E05.Dead Freight.it.srt
│   │   ├── Breaking Bad.S05E05.Dead Freight.mkv
│   │   ├── Breaking Bad.S05E05.Dead Freight.nfo
│   │   ├── Breaking Bad.S05E06.Buyout.it.srt
│   │   ├── Breaking Bad.S05E06.Buyout.mkv
│   │   ├── Breaking Bad.S05E06.Buyout.nfo
│   │   ├── Breaking Bad.S05E07.Say My Name.it.srt
│   │   ├── Breaking Bad.S05E07.Say My Name.mkv
│   │   ├── Breaking Bad.S05E07.Say My Name.nfo
│   │   ├── Breaking Bad.S05E08.Gliding Over All.it.srt
│   │   ├── Breaking Bad.S05E08.Gliding Over All.mkv
│   │   ├── Breaking Bad.S05E08.Gliding Over All.nfo
│   │   ├── Breaking Bad.S05E09.Blood Money.it.srt
│   │   ├── Breaking Bad.S05E09.Blood Money.mkv
│   │   ├── Breaking Bad.S05E09.Blood Money.nfo
│   │   ├── Breaking Bad.S05E10.Buried.it.srt
│   │   ├── Breaking Bad.S05E10.Buried.mkv
│   │   ├── Breaking Bad.S05E10.Buried.nfo
│   │   ├── Breaking Bad.S05E11.Confessions.it.srt
│   │   ├── Breaking Bad.S05E11.Confessions.mkv
│   │   ├── Breaking Bad.S05E11.Confessions.nfo
│   │   ├── Breaking Bad.S05E12.Rabid Dog.it.srt
│   │   ├── Breaking Bad.S05E12.Rabid Dog.mkv
│   │   ├── Breaking Bad.S05E12.Rabid Dog.nfo
│   │   ├── Breaking Bad.S05E13.To'hajiilee.it.srt
│   │   ├── Breaking Bad.S05E13.To'hajiilee.mkv
│   │   ├── Breaking Bad.S05E13.To'hajiilee.nfo
│   │   ├── Breaking Bad.S05E13.To'hajiilee-thumb.jpg
│   │   ├── Breaking Bad.S05E14.Ozymandias.it.srt
│   │   ├── Breaking Bad.S05E14.Ozymandias.mkv
│   │   ├── Breaking Bad.S05E14.Ozymandias.nfo
│   │   ├── Breaking Bad.S05E15.Granite State.it.srt
│   │   ├── Breaking Bad.S05E15.Granite State.mkv
│   │   ├── Breaking Bad.S05E15.Granite State.nfo
│   │   ├── Breaking Bad.S05E16.Felina.it.srt
│   │   ├── Breaking Bad.S05E16.Felina.mkv
│   │   ├── Breaking Bad.S05E16.Felina.nfo
│   │   └── season.nfo
│   ├── season05-poster.jpg
│   └── tvshow.nfo
├── Carnival Row
│   ├── clearlogo.png
│   ├── fanart.jpg
│   ├── landscape.jpg
│   ├── poster.jpg
│   ├── Season01
│   │   ├── Carnival Row.S01E01.Some Dark God Wakes.mkv
│   │   ├── Carnival Row.S01E01.Some Dark God Wakes.nfo
│   │   ├── Carnival Row.S01E01.Some Dark God Wakes.srt
│   │   ├── Carnival Row.S01E01.Some Dark God Wakes-thumb.jpg
│   │   ├── Carnival Row.S01E02.Aisling.mkv
│   │   ├── Carnival Row.S01E02.Aisling.nfo
│   │   ├── Carnival Row.S01E02.Aisling.srt
│   │   ├── Carnival Row.S01E02.Aisling-thumb.jpg
│   │   ├── Carnival Row.S01E03.Kingdoms of the Moon.mkv
│   │   ├── Carnival Row.S01E03.Kingdoms of the Moon.nfo
│   │   ├── Carnival Row.S01E03.Kingdoms of the Moon.srt
│   │   ├── Carnival Row.S01E03.Kingdoms of the Moon-thumb.jpg
│   │   ├── Carnival Row.S01E04.The Joining of Unlike Things.mkv
│   │   ├── Carnival Row.S01E04.The Joining of Unlike Things.nfo
│   │   ├── Carnival Row.S01E04.The Joining of Unlike Things.srt
│   │   ├── Carnival Row.S01E04.The Joining of Unlike Things-thumb.jpg
│   │   ├── Carnival Row.S01E05.Grieve No More.mkv
│   │   ├── Carnival Row.S01E05.Grieve No More.nfo
│   │   ├── Carnival Row.S01E05.Grieve No More.srt
│   │   ├── Carnival Row.S01E05.Grieve No More-thumb.jpg
│   │   ├── Carnival Row.S01E06.Unaccompanied Fae.mkv
│   │   ├── Carnival Row.S01E06.Unaccompanied Fae.nfo
│   │   ├── Carnival Row.S01E06.Unaccompanied Fae.srt
│   │   ├── Carnival Row.S01E06.Unaccompanied Fae-thumb.jpg
│   │   ├── Carnival Row.S01E07.The World to Come.mkv
│   │   ├── Carnival Row.S01E07.The World to Come.nfo
│   │   ├── Carnival Row.S01E07.The World to Come.srt
│   │   ├── Carnival Row.S01E07.The World to Come-thumb.jpg
│   │   ├── Carnival Row.S01E08.The Gloaming.mkv
│   │   ├── Carnival Row.S01E08.The Gloaming.nfo
│   │   ├── Carnival Row.S01E08.The Gloaming.srt
│   │   ├── Carnival Row.S01E08.The Gloaming-thumb.jpg
│   │   └── season.nfo
│   ├── season01-poster.jpg
│   └── tvshow.nfo

**Comment by iam4x** [comment]
I've pushed a fix on master, could you retry and tell me the result?

**Comment by mune360** [comment]
I've the same issue and it still not working.
There's a log of downloaded files that hasn't been "link" to the library/tvshow or movies.
It was working before I've moved the library folder to another location.

I cannot find any error related to this in the logs.... but here somes logs :

$ sudo docker container logs -f bobarr-api |egrep -i "LibraryService|ExceptionsHandler|Scan"

2020-06-22 00:00:02.489 [info] ScanLibrary - start scan library
2020-06-22 00:00:03.905 [info] ScanLibrary - start scan movies folder
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at /usr/src/app/node_modules/readdir-cluster/source/worker.js:24:12
    at FSReqCallback.oncomplete (fs.js:168:5)
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:310:20)
    at internal/child_process.js:683:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
2020-06-22 00:00:23.553 [info] ScanLibrary - start find new tvshow episodes
2020-06-22 00:00:23.812 [info] ScanLibrary - found 14 seasons
2020-06-22 00:00:24.868 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Condor","seasonNumber":2}
2020-06-22 00:00:25.019 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Penny Dreadful: City of Angels","seasonNumber":1}
2020-06-22 00:00:25.281 [info] ScanLibrary - found 0 new episodes - {"tvShow":"DuckTales","seasonNumber":1}
2020-06-22 00:00:25.519 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Teen Titans","seasonNumber":1}
2020-06-22 00:00:25.741 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Warehouse 13","seasonNumber":1}
2020-06-22 00:00:25.864 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Why Women Kill","seasonNumber":1}
2020-06-22 00:00:25.974 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Anne with an E","seasonNumber":3}
2020-06-22 00:00:26.132 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Home Before Dark","seasonNumber":1}
2020-06-22 00:00:26.268 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Batman Beyond","seasonNumber":1}
2020-06-22 00:00:26.404 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Batman: The Animated Series","seasonNumber":1}
2020-06-22 00:00:26.506 [info] ScanLibrary - found 0 new episodes - {"tvShow":"The New Batman Adventures","seasonNumber":2}
2020-06-22 00:00:26.641 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Marvel's Agents of S.H.I.E.L.D.","seasonNumber":7}
2020-06-22 00:00:26.925 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Brooklyn Nine-Nine","seasonNumber":7}
2020-06-22 00:00:27.191 [info] ScanLibrary - found 0 new episodes - {"tvShow":"Thieves of the Wood","seasonNumber":1}
2020-06-22 00:00:27.223 [info] ScanLibrary - finish find new tsvhow episodes
2020-06-22 06:00:00.776 [info] ScanLibrary - start scan library
2020-06-22 06:00:00.985 [info] ScanLibrary - start scan movies folder
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at /usr/src/app/node_modules/readdir-cluster/source/worker.js:24:12
    at FSReqCallback.oncomplete (fs.js:168:5)
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:310:20)
    at internal/child_process.js:683:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

**Comment by iam4x** [comment]
hey @mune360 this PR might have fixed your issue https://github.com/iam4x/bobarr/pull/167

I'll close this issue since the original issue is fixed.
