### ISSUE TITLE
Change API link

### ISSUE THREAD

**Issue by JerreBor** [iam4x/bobarr#128]
Hi there, I'm currently using nginx to reverse-proxy bobarr to my domain. I've seen that the app tries to make a request to `example.com:4000/graphql` but this doesn't work for me (because I'm using ssl, and the port 4000 isn't present). I've setup a domain `api.example.com` which I'd like the app to make it's requests to, but I can't seem to figure it out.

I've tried changing the file `appollo.config.js` in the root folder, but this doesn't seem to do anything.

Any help would be greatly appreciated!

**Comment by JerreBor** [comment]
Seemed to have fixed it by making some changes in the code at `/packages/web/utils/api-url.ts`. But now Jackett remains, anyone know where I should change that? Maybe something nice to add would be a .env entry for these things (or just a config file, I don't know)

**Comment by NicolasGuilloux** [comment]
Yeah, changing  `/packages/web/utils/api-url.ts` works. Remember to do a `docker-compose down; docker-compose up --build --force-recreate -d` after a change.

I would love to see and env variable too. Is it easy to do? We maybe can do a PR?

**Comment by iam4x** [comment]
Hey,

I've fixed it you can set `WEB_UI_API_URL` variable in `.env` to the API URL

**Comment by ronilaukkarinen** [comment]
I have the same issue. `WEB_UI_API_URL` seems to have no effect and I'm not exactly sure how to edit api-url.ts.

**Comment by pacholoamit** [comment]
Yeah, having the same issue. I tried changing the .env file but I still see the console making requests to the example.com:4000 domain. I also already did a ./bobarr.sh stop && ./bobarr.sh start

**Comment by fabioneves** [comment]
@iam4x also changed the env var, checked inside the WEB container and the env var is indeed there, but not effect whatsoever

**Comment by Hussienfahmy** [comment]
Could you please provide explanation about the domain in `WEB_UI_API_URL` what it should point to?

**Comment by zudsniper** [comment]
PSA: you can get this to work <sup><i>in a very hacky way</i></sup> by creating a `.env` file within `packages/web/` and putting your `WEB_UI_API_URL` definition there.

**Comment by nh-mike** [comment]
I found that I had to add `yarn build` to the bobarr-web container's command before it ran `yarn start`, in order for it to respect the environment variable.
